# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
